package com.sharewrap.sharewrap_backend.services;
// Generated by CodiumAI

import com.sharewrap.sharewrap_backend.dtos.LoginDto;
import com.sharewrap.sharewrap_backend.dtos.UserDto;
import com.sharewrap.sharewrap_backend.exceptions.AppException;
import com.sharewrap.sharewrap_backend.mappers.UserMapper;
import com.sharewrap.sharewrap_backend.models.User;
import com.sharewrap.sharewrap_backend.repositories.BillRepository;
import com.sharewrap.sharewrap_backend.repositories.UserRepository;
import org.mockito.Mockito;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.testng.annotations.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.Optional;

//import static org.junit.Assert.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class UserServiceTest {

    @Test
    public void test_valid_login_credentials_logging() {
        // Mock dependencies
        UserRepository userRepository = Mockito.mock(UserRepository.class);
        PasswordEncoder passwordEncoder = Mockito.mock(PasswordEncoder.class);
        UserMapper userMapper = Mockito.mock(UserMapper.class);
        BillRepository billRepository = Mockito.mock(BillRepository.class);

        // Create test data
        LoginDto loginDto = new LoginDto("test@example.com", "password".toCharArray()); //Get raw data
        User user = new User("test@example.com", "test");
        user.setPassword("abcde");

        // Mock repository methods
        Mockito.when(userRepository.findByEmail(loginDto.getEmail())).thenReturn(Optional.of(user));
        Mockito.when(passwordEncoder.matches(Mockito.any(CharSequence.class), Mockito.anyString())).thenReturn(true);

        // Create instance of UserService
        UserService userService = new UserService(userRepository, passwordEncoder, userMapper, billRepository);

        // Redirect console output to ByteArrayOutputStream
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        PrintStream printStream = new PrintStream(outputStream);
        System.setOut(printStream);

        // Invoke the method being tested
        userService.login(loginDto);

        // Restore console output
        System.setOut(System.out);

        // Assert the console output
        assertEquals("logging  in...", outputStream.toString().trim());
    }

    @Test
    public void test_invalid_login_credentials_log_message() {
        // Mock dependencies
        UserRepository userRepository = Mockito.mock(UserRepository.class);
        PasswordEncoder passwordEncoder = Mockito.mock(PasswordEncoder.class);
        UserMapper userMapper = Mockito.mock(UserMapper.class);
        BillRepository billRepository = Mockito.mock(BillRepository.class);

        // Create test data
        LoginDto loginDto = new LoginDto("test@example.com", "wrongPassword".toCharArray());
        User user = new User("test@example.com", "test");
        user.setPassword("encodedPassword");

        // Mock repository methods
        Mockito.when(userRepository.findByEmail(loginDto.getEmail())).thenReturn(Optional.of(user));
        Mockito.when(passwordEncoder.matches(Mockito.any(CharSequence.class), Mockito.anyString())).thenReturn(false);

        // Create instance of UserService
        UserService userService = new UserService(userRepository, passwordEncoder, userMapper, billRepository);

        // Redirect console output to ByteArrayOutputStream
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        PrintStream printStream = new PrintStream(outputStream);
        System.setOut(printStream);

        // Invoke the method being tested
        try {
            userService.login(loginDto);
        } catch (AppException e) {
            // Ignore exception
        }

        // Restore console output
        System.setOut(System.out);

        // Assert the log message
        assertEquals("Invalid password", outputStream.toString().trim());
    }
}